CREATE TABLE PLAYERS(ID string, FIRSTNAME string, LASTNAME string, FIRSTSEASON int, LASTSEASON int, WEIGHT int, BIRTHDATE date);

SELECT P1.FIRSTNAME, P1.LASTNAME
FROM PLAYERS P1, PLAYERS P2
WHERE P1.WEIGHT = P2.WEIGHT AND P1.WEIGHT = 325 AND FIRSTNAME='Priest';
